### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by art2engine** [zzzprojects/zzzcode.ai#15]
Have been trying to login with GitHub and google 
both do not work

**Comment by MUARDtaboub** [comment]
same problem mate ,what should we do ?

**Comment by JonathanMagnan** [comment]
Hello @art2engine , @MUARDtaboub 

Thank you for reporting.

We removed the login temporary till we find out the issue for Gmail. We fixed GitHub but there is still an issue with Gmail in some browsers only that we need to find out the reason.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @art2engine , @MUARDtaboub 

I will close the issue. Looking at the number of accounts we saw created daily, it looks like we successfully fixed the issue with Google.

If you still have a problem, just let me know and I will re-open this issue.

Best Regards,

Jon
