### ISSUE TITLE
unreal engine blueprint images (feature suggestion)

### ISSUE THREAD

**Issue by Omiyaru** [zzzprojects/zzzcode.ai#16]
i would love to see it be able to generate images of unreal blueprint examples implementations of code, 

 ive found that it actually attempts to do that sometimes ,but fails showing a broken image icon

**Comment by JonathanMagnan** [comment]
Hello @Omiyaru ,

I will close this issue as I don't think it will happen in the short term.

We currently don't plan to add image generation for this moment.

Best Regards,

Jon
