### ISSUE TITLE
website title typo

### ISSUE THREAD

**Issue by darshithpatel** [zzzprojects/zzzcode.ai#2]
Correct the website title '<title>ZZZ Code AI - **Finid** Any Programming Answers, Generate Code and More!</title>'
to '<title>ZZZ Code AI - **Find** Any Programming Answers, Generate Code and More!</title>'

<img width="386" alt="typo" src="https://github.com/zzzprojects/zzzcode.ai/assets/126161462/25957837-5603-4518-b358-d686cbffe3d8">

**Comment by JonathanMagnan** [comment]
Thank you for reporting @darshithpatel ,

It should be fixed tomorrow or later this week. We have a task to review all our titles to include more SEO keywords.

Best Regards,

Jon

**Comment by darshithpatel** [comment]
Thanks, Jon :)

**Comment by JonathanMagnan** [comment]
Hello @darshithpatel ,

Thank you again for reporting. This morning, all title & meta description on the website has been updated.

Have a great week,

Best Regards,

Jon
