### ISSUE TITLE
I got a sample code which does not work with the current interface of Ghostscript.NET

### ISSUE THREAD

**Issue by AK-Veritone** [zzzprojects/zzzcode.ai#21]
I entered the following phrase "Converting Multiple Page PDF to Images using Ghostscript.NET"

those commands returned an interface error
rasterizer.GhostscriptPath = @"C:\path\to\ghostscript\bin\gswin64c.exe";
 using (var image = rasterizer.GetPage(300, 300, pageNumber))

**Comment by JonathanMagnan** [comment]
Hello @AK-Veritone ,

There is nothing we can really do here. We only use the OpenAI API.

We can improve how it will answer, but we cannot check if the answer is right or wrong. 

The API will gives really good answers for popular topics but can also generate some bad code on less popular one.

Best Regards,

Jon
