### ISSUE TITLE
How to install matplotlib library?

### ISSUE THREAD

**Issue by sabina1122** [zzzprojects/zzzcode.ai#32]
How to install matplotlib library ?

**Comment by JonathanMagnan** [comment]
Hello @sabina1122 ,

You cannot install the `matplotlib` library on our website. 

You can see here how to do it: https://zzzcode.ai/answer-question?id=e865c735-e330-4190-8dfa-1c3ea388c47e

But that is the maximum support we can offer for this question, as this is not really related to our website, which is a question / generated answer. So we don't offer custom support for this kind of question.

Best Regards,

Jon
