### ISSUE TITLE
new code

### ISSUE THREAD

**Issue by Sunil-dh1234** [zzzprojects/zzzcode.ai#42]
Tasks To Be Performed:
1. Search the elements by name and by link text
2. Search elements using CSS
3. Store elements
4. Insert comments in IDE
5. Record and add commands in a test
6. Execute all Selenium commands in IDE
7. Create test suites
8. Start and Stop the Selenium RC from Eclipse
9. Write Selenium test script
10. Generate reports using TestNG
11.Create test suites with TestNG
12. Create POM.xml file

**Comment by JonathanMagnan** [comment]
Hello @Sunil-dh1234 ,

Is there any question/request in your text?

**Comment by JonathanMagnan** [comment]
Your text doesn't look to contain any issue, so it will be closed. Feel free to explain what your reported this in a new issue if you want we answer something
