### ISSUE TITLE
Dataframe of phytochemicals

### ISSUE THREAD

**Issue by Mrinmoy57** [zzzprojects/zzzcode.ai#43]
import pandas as pd
import requests
from io import StringIO

# Function to download and load data into a DataFrame
def download_and_load_data(url):
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an exception for bad status codes

        if response.text:
            data = StringIO(response.text)
            df = pd.read_csv(data)
            print("Dataset loaded successfully into a DataFrame.")
            return df
        else:
            print("No data found in the response.")
            return None

    except requests.exceptions.RequestException as e:
        print(f"Error downloading data: {e}")
        return None
    except pd.errors.EmptyDataError:
        print("Empty data received.")
        return None
    except pd.errors.ParserError:
        print("Error parsing the data.")
        return None
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

# Function to save DataFrame to a CSV file
def save_to_csv(df, filename):
    try:
        if df is not None:
            df.to_csv(filename, index=False)
            print("Data saved to CSV successfully.")
        else:
            raise Exception("No DataFrame to save.")
    except Exception as e:
        print("Error saving data to CSV:", e)

# Example usage
url = "https://cb.imsc.res.in/imppat/basicsearch/phytochemical"
df = download_and_load_data(url)

if df is not None:
    save_to_csv(df, 'downloaded_data.csv')

**Comment by JonathanMagnan** [comment]
Your text doesn't look to contain any issue, so it will be closed. Feel free to explain what your reported this in a new issue if you want we answer something
