### ISSUE TITLE
zzzcode.ai is not available

### ISSUE THREAD

**Issue by shekhardhar** [zzzprojects/zzzcode.ai#45]
Thank you for creating this product. I truly appreciate all the hard work you have put into this. I know you are providing these amazing services to us for free. I just want to know what the current state of your application because zzzcode.ai is showing as Service Unavailable.

**Comment by JonathanMagnan** [comment]
Hello @shekhardhar ,

It's the first time the application pool has failed to start this morning.

We added an alert (I though we already had one!) that will let us know whenever the website is down so we should be able to react faster the next time it happens.

Thank you for your great feedback, I'm always happy to hear that people love to use it.

Best Regards,

Jon
