### ISSUE TITLE
Problem report

### ISSUE THREAD

**Issue by Naoufal-Charafat** [zzzprojects/zzzcode.ai#46]
Oops! A general error occurred: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - No connection could be made because the target machine actively refused it.). NOTE: This error is usually caused by OpenAI service that are down: https://status.openai.com/

**Comment by JonathanMagnan** [comment]
Thank you for reporting @Naoufal-Charafat ,

Our SQL Server instance indeed crashed a few days ago.

We moved some websites from the server to reduce the load and are currently trying to find out what caused it (the first time in about 8 years that the SQL Server crashed).

Feel free to report it if it happens again, but we will currently close this issue as it looks to be a single-event issue.

Best Regards,

Jon
