### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MalwareLabx** [zzzprojects/zzzcode.ai#48]
When using the convert from to function, it doesn't work, the code is only one third
![image](https://github.com/zzzprojects/zzzcode.ai/assets/164758246/80dcae10-690b-4286-91b4-e272f7596be3)
![image](https://github.com/zzzprojects/zzzcode.ai/assets/164758246/956b2ead-6566-4886-81fd-bad5cb2b11f4)

**Comment by JonathanMagnan** [comment]
Hello @MATTIAloyoutuber ,

Unfortunately, we do not control exactly what is generated by OpenAI.

We just send some prompt and hope like you that the answer will be good enough for your need.

Best Regards,

Jon
