### ISSUE TITLE
Issue to output of the code

### ISSUE THREAD

**Issue by sabina1122** [zzzprojects/zzzcode.ai#49]
Hi Jon, 
While using zzz code to generate code using AI, I was unsuccessful in generating the required output. Do you have team who can help put together a professional code that would help automate certain task which would be helpful for greater good?

I can provide you with the detailed specification. 
Would be your hourly rate for putting together a Python Code/C ++ Code ? 

Thanks
Shinu

**Comment by JonathanMagnan** [comment]
Hello @sabina1122 ,

Unfortunately, we currently have barely the time to do all the tasks  we planned for 2024.

Perharp UpWorks might be a better solution for you.

Best Regards,

Jon
