### ISSUE TITLE
visual basic 6 Comments to c#

### ISSUE THREAD

**Issue by Rubenzgb** [zzzprojects/zzzcode.ai#5]
Converting the code from Visual Basic 6 to C#, the code converter removes the vb6 comments, for example:
' If mbytServiceType = 2 And mintService = 20 Then
' mstrMotion_Type = "LOW"
' End If

It would be good if the comments were converted to c# comments in the following way

// If mbytService_Type = 2 And mintService = 20 Then
// mstrMovement_Type = "LOW"
//EndIf

It doesn't matter that the comment is converted into original code.

**Comment by JonathanMagnan** [comment]
Hello @Rubenzgb ,

Thank you for this good suggestion.

We chose to keep the comment as the original code. Make more sense to us.

It should now work as expected most of the time (we can only provide instruction but cannot control 100% what ChatGPT will output): https://zzzcode.ai/code-converter?id=2087ae4e-181d-4423-bb93-8f6f68a4be78

Best Regards,

Jon
