### ISSUE TITLE
abolfazl

### ISSUE THREAD

**Issue by abolfazletehad2887** [zzzprojects/zzzcode.ai#55]
.content {
    position: relative;
    width: calc(var(--sz) * 5);
    height: calc(var(--sz) * 3);
    display: flex;
    align-items: center;
    justify-content: center;
}

**Comment by abolfazletehad2887** [comment]
good

**Comment by abolfazletehad2887** [comment]
good

**Comment by JonathanMagnan** [comment]
Hello @abolfazletehad2887 ,

I will close this issues as I have no idea what you are trying to do.

Best Regards,

Jon
