### ISSUE TITLE
Missing signature on QueryAsync method

### ISSUE THREAD

**Issue by FabienEstier** [zzzprojects/zzzcode.ai#59]
I'm using this method signature for QueryAsync:
public static Task<IEnumerable<TReturn>> QueryAsync<TReturn>(this IDbConnection cnn, string sql, Type[] types, Func<object[], TReturn> map, object? param = null, IDbTransaction? transaction = null, bool buffered = true, string splitOn = "Id", int? commandTimeout = null, CommandType? commandType = null)

I need to pass a Cancellation token but there is no available signature with Type[] types, Func<object[], TReturn> map and string splitOn parameters. I tried to used the signature with a CommandDefinition object because it contains a property named CancellationToken but this signature doesn't contain types, map and splitOn too.
Is it possible to add it in a future release ?

**Comment by JonathanMagnan** [comment]
Hello @FabienEstier ,

It depends. Are you talking about an issue using the AI for Dapper or a new method Dapper itself?

I could be wrong, but your request might be more for Dapper directly: https://github.com/DapperLib/Dapper/issues

Best Regards,

Jon

**Comment by FabienEstier** [comment]
Thanks :)
