### ISSUE TITLE
I cannot access 

### ISSUE THREAD

**Issue by GlennBonde** [zzzprojects/zzzcode.ai#63]
Hi,

I wanted to test https://zzzcode.ai/javascript/code-explain. My script was about 8000 chars so I logged in using my GitHub account. Once logged in, I was redirected to https://sqlfiddle.com/???

I think this is a bug.

BR,
Glenn

**Comment by JonathanMagnan** [comment]
Hello @GlennBonde ,

Thank you for reporting. I indeed have the same behavior.

I'm currently working on it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @GlennBonde ,

The issue should be fixed.

Let me know if the login is now working as expected (redirecting to the right website).

Best Regards,

Jon

**Comment by GlennBonde** [comment]
Hi @JonathanMagnan,

Great! It now works for me as well  :-)
Best regards,
Glenn
