### ISSUE TITLE
option to use gpt-4o or gpt-4o mini

### ISSUE THREAD

**Issue by Fesuoy1** [zzzprojects/zzzcode.ai#67]
self explanatory, i heard using gpt-4o's API can be cheaper than normal GPT-3.5, So I'd recommend using it tbh (yes i cant think of better description for this suggestion)

**Comment by vsjsan** [comment]
نضام محاسبة

**Comment by JonathanMagnan** [comment]
Hello @Fesuoy1 ,

You are right, `gpt-4o mini` is WAY cheaper, better, and probably faster. We updated our website to use this model on August 12.

It currently reduces the cost by 66%, so this is huge for us.

This new cost allows us to rethink this website to include chat, modify answers, etc.

Let me know if that answer correctly to your question.

Best Regards,

Jon
