### ISSUE TITLE
incomplete code

### ISSUE THREAD

**Issue by alhaines** [zzzprojects/zzzcode.ai#68]
This app does not generate complete code or sql!
There were many parts missing, where it said add your code here.  good thing I didn't pay for this.

**Comment by JonathanMagnan** [comment]
Hello @alhaines ,

What is returned is what [OpenAI](https://openai.com/) API returns. We don't control this.

> good thing I didn't pay for this.

Indeed, **I'm the one** who pays for it and offers it worldwide for **FREE**.

I understand your frustration, but please, as a **good communicator**, next time, share the URL of what has been generated so we can try to at least understand what happened and improve it.

Best Regards,

Jon
