### ISSUE TITLE
A web base asset management software

### ISSUE THREAD

**Issue by simphen20** [zzzprojects/zzzcode.ai#69]
Generate for me a complete web base Asset management system by name of 'K-net asset manager' that works exactly like 'Kaizen Asset Manager Enterprise 2012'/ Ensure the first opening page has Create company, Register user, and login forms. Any new user registered has to have to select a company he/she is working with. Users will have no access to information of another company he/she is not registred. First user to create a company, automatically becomes an Admin of that Company. Other features of the system include, recording of new asset, transfer of assets between custodians, checkin and chechout of asset for repair. The system has to generate reports in either of the following, by custodian, by category, by location, by status, etc. all those should be chosen in filters. generate a code files showing the location structure, ensure they connect using the following: Hostname= localhost, Username = root, password= '' and Database name= 'K-net asset manager' ensure files include SQL. And please generate a downloadable zip file, after coding. Thanks

**Comment by JonathanMagnan** [comment]
Hello @simphen20 ,

We will close this issue as this currently doesn't look like an issue but more copy & past of a prompt.

So, there is currently an issue/question in your text.

Best Regards,

Jon
