### ISSUE TITLE
query limit issue

### ISSUE THREAD

**Issue by NalluriSreekanth** [zzzprojects/zzzcode.ai#75]
i had created an account and also logged into the account but it is showing 5000 character limit

**Comment by JonathanMagnan** [comment]
Hello @NalluriSreekanth ,

The limit has been increased to 10k for unlogged users and 20k for logged users.

I tested a 19k characters text; it was not working as intended if I was not logged but it worked correctly if I logged in.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @NalluriSreekanth ,

I will close this issue has the limit has been increased and I didn't get any answer from you.

Best Regards,

Jon
